### ISSUE TITLE
Webpage/dashboard blank

### ISSUE THREAD

**Issue by meghakundu** [TheCoderRaman/UyScuti#5]
![image](https://github.com/user-attachments/assets/3f345456-ee80-4910-ad93-6cadfe703a11)

Please help with this @TheCoderRaman

**Comment by TheCoderRaman** [comment]
I understand you're encountering difficulties building the project. 
To assist you further, please confirm the following:

### Correctly build the project using
```sh
npm run build
```

If not then execute the following commands in your terminal
Here are some common dependencies that might be required:
> Node.js: The primary runtime environment for JavaScript execution on the server side.
> npm: The Node Package Manager, used to install, manage, and update dependencies.

```sh
# Install dependencies
npm install --legacy-peer-deps  --force
# Build the project
npm run build
```

### After building run the laravel app using
Before proceeding, please ensure you've thoroughly reviewed the project's README file. Specially
https://github.com/TheCoderRaman/UyScuti#install-laravel-backend

```sh
php artisan serve
```

## Here is the final result
![Opera Snapshot_2024-09-25_221341_127 0 0 1](https://github.com/user-attachments/assets/7c018b37-c342-446c-bd06-29dfa85b1aa0)


If you have any other query then feel free to ask me
@meghakundu

**Comment by TheCoderRaman** [comment]
If you're encountering difficulties building the project, 
you can use the provided pre-built project files for a quicker setup.

### Instructions:
* Extract Files: Extract the pre-built project files to the root public directory of your project.
```sh
public
```

Note: Using pre-built files can expedite the setup process, especially if you're facing build errors or limitations.

## Here is final build
[build.zip](https://github.com/user-attachments/files/17135030/build.zip)

**Comment by meghakundu** [comment]
> If you're encountering difficulties building the project, you can use the provided pre-built project files for a quicker setup.
> 
> ### Instructions:
> * Extract Files: Extract the pre-built project files to the root public directory of your project.
> 
> ```shell
> public
> ```
> 
> Note: Using pre-built files can expedite the setup process, especially if you're facing build errors or limitations.
> 
> ## Here is final build
> [build.zip](https://github.com/user-attachments/files/17135030/build.zip)

Still same!

**Comment by TheCoderRaman** [comment]
Could you please provide the console error from the browser

**Comment by meghakundu** [comment]
> Could you please provide the console error from the browser

![image](https://github.com/user-attachments/assets/1ca3a890-daf3-4b35-aa6e-2e63ec66fa33)
Please help with this @TheCoderRaman

**Comment by TheCoderRaman** [comment]
To assist in diagnosing and resolving the issues you're encountering with UyScuti, 
please provide the following information:

### Browser Console Logs:
Access Console: Open UyScuti in your web browser and press Ctrl+Shift+I (or equivalent) to open the developer console.
Capture Errors: Look for any error messages or warnings displayed in the console. If possible, copy and paste the relevant logs into your response.

![console-error](https://github.com/user-attachments/assets/f812ee83-0a91-4c82-b03e-f129a91e3503)

**Comment by TheCoderRaman** [comment]
### A video tutorial showcasing the step-by-step installation of UyScuti

https://github.com/user-attachments/assets/a787b166-c133-444f-b909-b852a8ca7f36

**Comment by meghakundu** [comment]
> ```shell
> npm install --legacy-peer-deps  --force
> ```

Thanks for the above, I had followed the same procedure for installation. But found such error in the console
![image](https://github.com/user-attachments/assets/1fb433f6-1a1e-4ceb-855d-cea9f6b9519a)
I hope you get it. @TheCoderRaman

**Comment by TheCoderRaman** [comment]
## Issue: Invalid JSON in Browser Local Storage

The application attempts to load configuration data from the browser’s local storage, but the data stored is not valid JSON.

Steps to Debug:
Open the website in an incognito window to start with a fresh environment.
If the application loads without any issues, the problem likely lies with the data stored in the local storage.

Solution:
If the above step works, run the following code in the browser where the problem occurs:
Open the developer console by pressing `Ctrl+Shift+I`.
Execute the following command to clear the local storage:

https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage
```sh
localStorage.clear();
```

Refresh the browser.
If the application works after this, it indicates that something went wrong during the previous data storage process.

**Comment by meghakundu** [comment]
> ## Issue: Invalid JSON in Browser Local Storage
> The application attempts to load configuration data from the browser’s local storage, but the data stored is not valid JSON.
> 
> Steps to Debug: Open the website in an incognito window to start with a fresh environment. If the application loads without any issues, the problem likely lies with the data stored in the local storage.
> 
> Solution: If the above step works, run the following code in the browser where the problem occurs: Open the developer console by pressing `Ctrl+Shift+I`. Execute the following command to clear the local storage:
> 
> https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage
> 
> ```shell
> localStorage.clear();
> ```
> 
> Refresh the browser. If the application works after this, it indicates that something went wrong during the previous data storage process.
Thanks
